### ISSUE TITLE
Immutablejs support

### ISSUE THREAD

**Issue by kovcic** [ioof-holdings/redux-dynamic-reducer#9]
I have entire state as immutable.js object. From what I have seen this lib doesn't support that case. Correct me if I'm wrong or share a tip if possible to use it that way. Thx

**Comment by mpeyper** [comment]
Hi @kovcic,

We have not explicitly tried to support immutablejs in this library.  We have also not explicitly tried to prevent it from working.

From memory, Redux's `combineReducers` function does not work with the immutablejs structures, so that is likely the main reason preventing it from working (and all the other ways we merge and wrap the reducers).

I'm more than happy to look at a PR the adds support, or even to help with the changes.
